<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CardSeeder extends Seeder
{

    public function run(): void
    {
        $cards = [
            [
                'titulo' => 'Tu Bar, en la Mira',
                'descripcion' => 'Haz que el nombre de tu bar destaque con letras neón LED. Crea un ambiente único que atraiga miradas y clientes. ¡Ilumina tu identidad! 🍹🔆',
                'public_image' => '/blog/fondo_blog_extend.webp',
                'id_plantilla' => 1,
                'id_blog' => 1,
                'id_empleado' => 2,
                'estado_publicacion' => 1,
                'created_at' => '2025-10-15 10:30:00',
                'updated_at' => '2025-10-15 10:30:00',
            ],
            [
                'titulo' => 'Moderniza tu Pizzería',
                'descripcion' => 'Crea una experiencia italiana con toques modernos. Iluminación que realza la calidez del horno de leña. Ambiente perfecto para una cena inolvidable. 🍕✨',
                'public_image' => '/blog/fondo_blog_extend.webp',
                'id_plantilla' => 2,
                'id_blog' => 2,
                'id_empleado' => 3,
                'estado_publicacion' => 1,
                'created_at' => '2025-11-08 14:20:00',
                'updated_at' => '2025-11-08 14:20:00',
            ],
            [
                'titulo' => 'Transformación Digital para tu Restaurante',
                'descripcion' => 'El primer impacto decide. Iluminación LED que reduce consumo energético en 80% mientras mejora la experiencia visual. Eficiencia y estética juntas. 💡🚀',
                'public_image' => '/blog/fondo_blog_extend.webp',
                'id_plantilla' => 3,
                'id_blog' => 3,
                'id_empleado' => 4,
                'estado_publicacion' => 1,
                'created_at' => '2025-12-20 11:45:00',
                'updated_at' => '2025-12-20 11:45:00',
            ],
            [
                'titulo' => 'Cafés Premium - Ambiance que Vende',
                'descripcion' => 'Tu café es más que bebida, es experiencia. Crea espacios instagrameables donde los clientes quieran quedarse y compartir. ☕📸',
                'public_image' => '/blog/fondo_blog_extend.webp',
                'id_plantilla' => 1,
                'id_blog' => 4,
                'id_empleado' => 5,
                'estado_publicacion' => 1,
                'created_at' => '2025-11-25 09:15:00',
                'updated_at' => '2025-11-25 09:15:00',
            ],
            [
                'titulo' => 'Hoteles de Lujo - Primera Impresión',
                'descripcion' => 'El lobby define la experiencia. Iluminación que transmite lujo y exclusividad desde el primer paso. Cada detalle cuenta. 🏨👑',
                'public_image' => '/blog/fondo_blog_extend.webp',
                'id_plantilla' => 2,
                'id_blog' => 5,
                'id_empleado' => 2,
                'estado_publicacion' => 1,
                'created_at' => '2025-10-30 15:40:00',
                'updated_at' => '2025-10-30 15:40:00',
            ],
            [
                'titulo' => 'Retail - Estrategia Visual para Aumentar Ventas',
                'descripcion' => 'El comportamiento de compra comienza con la iluminación. Estudios demuestran que clientes pasan 35% más tiempo y compran 40% más. 💳📈',
                'public_image' => '/blog/fondo_blog_extend.webp',
                'id_plantilla' => 3,
                'id_blog' => 6,
                'id_empleado' => 6,
                'estado_publicacion' => 1,
                'created_at' => '2025-12-03 08:22:00',
                'updated_at' => '2025-12-03 08:22:00',
            ],
            [
                'titulo' => 'Bares Nocturnos - Atmósfera Vibrante',
                'descripcion' => 'La noche viene viva con sistemas LED dinámicos que responden a música. Crea vibraciones visuales que cautiven a tus clientes. 🎶✨',
                'public_image' => '/blog/fondo_blog_extend.webp',
                'id_plantilla' => 1,
                'id_blog' => 7,
                'id_empleado' => 3,
                'estado_publicacion' => 1,
                'created_at' => '2025-11-12 16:50:00',
                'updated_at' => '2025-11-12 16:50:00',
            ],
            [
                'titulo' => 'Galerías de Arte - Luz que Destaca Obras',
                'descripcion' => 'Cada obra merece iluminación perfecta. Sistemas especializados que preservan y realzan cada detalle sin dañar lienzos o esculturas. 🎨💎',
                'public_image' => '/blog/fondo_blog_extend.webp',
                'id_plantilla' => 2,
                'id_blog' => 8,
                'id_empleado' => 4,
                'estado_publicacion' => 1,
                'created_at' => '2025-10-22 12:10:00',
                'updated_at' => '2025-10-22 12:10:00',
            ],
            [
                'titulo' => 'Gimnasios Modernos - Energía Visual',
                'descripcion' => 'Iluminación que motiva el entrenamiento. Cada zona con su propia atmósfera: energizante en cardio, motivacional en pesas, relajante en estiramientos. 💪⚡',
                'public_image' => '/blog/fondo_blog_extend.webp',
                'id_plantilla' => 3,
                'id_blog' => 9,
                'id_empleado' => 5,
                'estado_publicacion' => 1,
                'created_at' => '2025-12-10 13:35:00',
                'updated_at' => '2025-12-10 13:35:00',
            ],
            [
                'titulo' => 'Spas de Relajación - Serenidad Iluminada',
                'descripcion' => 'La luz perfecta para inducir calma total. Diseñada científicamente para reducir estrés y mejorar percepción de bienestar en cada sesión. 🧘‍♀️🌙',
                'public_image' => '/blog/fondo_blog_extend.webp',
                'id_plantilla' => 1,
                'id_blog' => 10,
                'id_empleado' => 2,
                'estado_publicacion' => 1,
                'created_at' => '2025-11-05 10:05:00',
                'updated_at' => '2025-11-05 10:05:00',
            ],
            // Enero 2026
            [
                'titulo' => 'Boutiques de Lujo - Tiendas Exclusivas',
                'descripcion' => 'Ambiente de exclusividad con iluminación que realza cada pieza. Los clientes VIP merecen una experiencia visual de nivel premium. 💎✨',
                'public_image' => '/blog/fondo_blog_extend.webp',
                'id_plantilla' => 2,
                'id_blog' => 11,
                'id_empleado' => 3,
                'estado_publicacion' => 1,
                'created_at' => '2026-01-05 09:20:00',
                'updated_at' => '2026-01-05 09:20:00',
            ],
            [
                'titulo' => 'Restaurantes Finos - Elegancia Gastronómica',
                'descripcion' => 'Iluminación que complementa la propuesta culinaria. Ambiente sofisticado que invita a disfrutar al máximo cada plato. 🍽️👨‍🍳',
                'public_image' => '/blog/fondo_blog_extend.webp',
                'id_plantilla' => 3,
                'id_blog' => 12,
                'id_empleado' => 4,
                'estado_publicacion' => 1,
                'created_at' => '2026-01-12 14:45:00',
                'updated_at' => '2026-01-12 14:45:00',
            ],
            [
                'titulo' => 'Museos - Iluminación Patrimonial',
                'descripcion' => 'Preservar la historia con luz correcta. Sistemas que realzan artefactos históricos sin comprometer su integridad. 🏛️📜',
                'public_image' => '/blog/fondo_blog_extend.webp',
                'id_plantilla' => 1,
                'id_blog' => 13,
                'id_empleado' => 5,
                'estado_publicacion' => 1,
                'created_at' => '2026-01-18 11:30:00',
                'updated_at' => '2026-01-18 11:30:00',
            ],
            [
                'titulo' => 'Cines Modernos - Experiencia Cinematográfica',
                'descripcion' => 'Ambientes de espera que generan anticipación. Pasillos, salas de espera y áreas comerciales con iluminación estratégica que atrae. 🎬🍿',
                'public_image' => '/blog/fondo_blog_extend.webp',
                'id_plantilla' => 2,
                'id_blog' => 14,
                'id_empleado' => 6,
                'estado_publicacion' => 1,
                'created_at' => '2026-01-25 16:15:00',
                'updated_at' => '2026-01-25 16:15:00',
            ],
            // Febrero 2026
            [
                'titulo' => 'Oficinas Corporativas - Productividad Lumínica',
                'descripcion' => 'Iluminación que potencia concentración y reduce fatiga visual. Espacios donde tus equipos rinden al máximo. 🏢💡',
                'public_image' => '/blog/fondo_blog_extend.webp',
                'id_plantilla' => 3,
                'id_blog' => 15,
                'id_empleado' => 2,
                'estado_publicacion' => 1,
                'created_at' => '2026-02-03 08:50:00',
                'updated_at' => '2026-02-03 08:50:00',
            ],
            [
                'titulo' => 'Clínicas Estéticas - Ambientes Sanadores',
                'descripcion' => 'Iluminación que transmite confianza y serenidad. Los pacientes merecen espacios que inspiren seguridad en los tratamientos. 👩‍⚕️✨',
                'public_image' => '/blog/fondo_blog_extend.webp',
                'id_plantilla' => 1,
                'id_blog' => 16,
                'id_empleado' => 3,
                'estado_publicacion' => 1,
                'created_at' => '2026-02-10 13:25:00',
                'updated_at' => '2026-02-10 13:25:00',
            ],
            [
                'titulo' => 'Hoteles Económicos - Comodidad Iluminada',
                'descripcion' => 'Maximizar confort con presupuesto inteligente. Iluminación eficiente que crea espacios acogedores sin gastar de más. 💰🛏️',
                'public_image' => '/blog/fondo_blog_extend.webp',
                'id_plantilla' => 2,
                'id_blog' => 17,
                'id_empleado' => 4,
                'estado_publicacion' => 1,
                'created_at' => '2026-02-17 10:40:00',
                'updated_at' => '2026-02-17 10:40:00',
            ],
            [
                'titulo' => 'Eventos - Iluminación Espectacular',
                'descripcion' => 'Crea momentos memorables con luz dinámica. Desde bodas hasta conciertos, la iluminación define la experiencia. 🎉🎆',
                'public_image' => '/blog/fondo_blog_extend.webp',
                'id_plantilla' => 3,
                'id_blog' => 18,
                'id_empleado' => 5,
                'estado_publicacion' => 1,
                'created_at' => '2026-02-24 15:55:00',
                'updated_at' => '2026-02-24 15:55:00',
            ],
        ];

        foreach ($cards as $card) {
            DB::table('cards')->insert($card);
        }
    }
}
